# Generated by Django 5.2 on 2025-04-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("religious_atlas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="founding_period",
            field=models.CharField(
                blank=True,
                help_text="Describe when the church was founded ('12th century', '1888', 'c. 1950')",
                max_length=100,
                verbose_name="Founding Period",
            ),
        ),
        migrations.AlterField(
            model_name="religion",
            name="founded_date",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Describe when the religion was founded ('1st century AD', '7th century CE', '1830s' etc)",
                max_length=100,
                verbose_name="Founded Period/Date",
            ),
            preserve_default=False,
        ),
    ]
